name: "PR Title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        name: "Check PR Title"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
